In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from wordcloud import WordCloud

#to data preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#NLP tools
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

#train split and fit models
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

#model selection
from sklearn.metrics import confusion_matrix, accuracy_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
!cp gdrive/MyDrive/preparedDataSet3.pkl .
import pandas as pd

In [ ]:
dataset = pd.read_pickle("preparedDataSet3.pkl")
dataset.head(10)

par_id                                           sentence  label
8738   9649  "an analysis of requests by federal officials ...      0
1184   6715  so assured government assistance in future for...      1
2572   3489  mr vigbedor urged the traditional leaders to b...      1
1103   1237  "mai chen , founder of myadvice.legal , said "...      0
5173   5708  the study showed that as many as 80 percent of...      0
8800   9723  following the main launch , at which the exhib...      0
711     790  """ we know that the success of any society de...      0
7049   7796  "the newspaper report came amid concerns over ...      0
7262   8029  """ we are proud to host an artist like kesha ...      0
6963   7703  severe cold wave is sweeping over kurigram cau...      0

In [ ]:
dataset.shape

(12236, 3)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12236 entries, 8738 to 371
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   par_id    12236 non-null  object
 1   sentence  12236 non-null  object
 2   label     12236 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 382.4+ KB


In [ ]:
dataset.describe().T

count      mean      std  min  25%  50%  75%  max
label  12236.0  0.225564  0.41797  0.0  0.0  0.0  0.0  1.0

In [ ]:
dt_trasformed = dataset[['label', 'sentence']]
y = dt_trasformed.iloc[:, :-1].values

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = np.array(ct.fit_transform(y))

In [ ]:
y[:10]

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
print(y)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]


In [ ]:
y_df = pd.DataFrame(y)

In [ ]:
np.array(y_df[0])

array([1., 0., 0., ..., 1., 1., 0.])

In [ ]:
np.array(y_df[1])

array([0., 1., 1., ..., 0., 0., 1.])

In [ ]:
dataset['sentence'].values

array(['"an analysis of requests by federal officials for local jails to keep immigrants suspected of violating us immigration law in custody found half of the so-called "" holds "" were placed on people who had been arrested but actually had no criminal conviction ."',
       'so assured government assistance in future for such initiatives . according to amod kanth , founder and general secretary , prayas jac society , said the library will instill a sense of confidence in the homeless and will help in changing their perspective towards life ."',
       'mr vigbedor urged the traditional leaders to be ambassadors in their respective communities to help reduce stigma and restore hope to such vulnerable groups .',
       ...,
       'but he said the findings should not be taken as a sign that women should seek an appendectomy or tonsillectomy thinking it could increase their chances of becoming pregnant .',
       'it is more like a town than a refugee camp .',
       ' space of a week 

In [ ]:
cv = CountVectorizer(max_features = 2000)
X = cv.fit_transform(dataset['sentence'].values).toarray()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_df[1], test_size = 0.20, random_state = 0)

Finding the best models to predict 

Naive Bayes



In [ ]:
classifier_np = GaussianNB()
classifier_np.fit(X_train, y_train)

GaussianNB()

Decision Tree

In [ ]:
classifier_dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

KNN

In [ ]:
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier()

Logistic Regression



In [ ]:
classifier_lr = LogisticRegression(random_state = 0)
classifier_lr.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

Random Forest



In [ ]:
classifier_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

SVM Classifier



In [ ]:
classifier_svm = svm.SVC()
classifier_svm.fit(X_train, y_train)

SVC()

XGBoost Classifier



In [ ]:
classifier_xgb= XGBClassifier()
classifier_xgb.fit(X_train, y_train)

XGBClassifier()

Making the Confusion Matrix for each model


In [ ]:
#Naive Bayes
y_pred_np = classifier_np.predict(X_test)
cm = confusion_matrix(y_test, y_pred_np)
print(cm)

[[1032  853]
 [  63  500]]


In [ ]:
#KNN
y_pred_knn = classifier_knn.predict(X_test)
cm = confusion_matrix(y_test, y_pred_knn)
print(cm)

[[1736  149]
 [ 283  280]]


In [ ]:
#XGBoost Classifier
y_pred_xgb = classifier_xgb.predict(X_test)
cm = confusion_matrix(y_test, y_pred_xgb)
print(cm)

[[1858   27]
 [ 420  143]]


In [ ]:
#SVM
y_pred_svm = classifier_svm.predict(X_test)
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)

[[1861   24]
 [ 215  348]]


In [ ]:
#Logistic Regression
y_pred_lr=classifier_lr.predict(X_test)
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)

[[1733  152]
 [ 186  377]]


In [ ]:
#Decision Tree
y_pred_dt = classifier_dt.predict(X_test)
cm = confusion_matrix(y_test, y_pred_dt)
print(cm)

[[1677  208]
 [ 103  460]]


In [ ]:
#Random Florest
y_pred_rf = classifier_rf.predict(X_test)
cm = confusion_matrix(y_test, y_pred_rf)
print(cm)

[[1866   19]
 [ 169  394]]


In [ ]:
rf_score = accuracy_score(y_test, y_pred_rf)
knn_score = accuracy_score(y_test, y_pred_knn)
svm_score = accuracy_score(y_test, y_pred_svm)
xgb_score = accuracy_score(y_test, y_pred_xgb)
lr_score = accuracy_score(y_test, y_pred_lr)
dt_score = accuracy_score(y_test, y_pred_dt)
np_score = accuracy_score(y_test, y_pred_np)

print('Random Forest Accuracy: ', str(rf_score))
print('K Nearest Neighbours Accuracy: ', str(knn_score))
print('Support Vector Machine Accuracy: ', str(svm_score))
print('XGBoost Classifier Accuracy: ', str(xgb_score))
print('Logistic Regression Accuracy: ',str(lr_score))
print('Decision Tree Accuracy: ', str(dt_score))
print('Naive Bayes Accuracy: ', str(np_score))

Random Forest Accuracy:  0.923202614379085
K Nearest Neighbours Accuracy:  0.8235294117647058
Support Vector Machine Accuracy:  0.9023692810457516
XGBoost Classifier Accuracy:  0.8174019607843137
Logistic Regression Accuracy:  0.8619281045751634
Decision Tree Accuracy:  0.8729575163398693
Naive Bayes Accuracy:  0.6258169934640523


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
class_names = ['Not Patronizing','Is Patronizing']
print(classification_report(y_test, y_pred_rf, target_names=class_names))
print(confusion_matrix(y_test, y_pred_rf))

                 precision    recall  f1-score   support

Not Patronizing       0.92      0.99      0.95      1885
 Is Patronizing       0.95      0.70      0.81       563

       accuracy                           0.92      2448
      macro avg       0.94      0.84      0.88      2448
   weighted avg       0.93      0.92      0.92      2448

[[1866   19]
 [ 169  394]]


In [ ]:
print(classification_report(y_test, y_pred_knn, target_names=class_names))
print(confusion_matrix(y_test, y_pred_knn))

                 precision    recall  f1-score   support

Not Patronizing       0.86      0.92      0.89      1885
 Is Patronizing       0.65      0.50      0.56       563

       accuracy                           0.82      2448
      macro avg       0.76      0.71      0.73      2448
   weighted avg       0.81      0.82      0.81      2448

[[1736  149]
 [ 283  280]]


In [ ]:
print(classification_report(y_test, y_pred_svm, target_names=class_names))
print(confusion_matrix(y_test, y_pred_svm))

                 precision    recall  f1-score   support

Not Patronizing       0.90      0.99      0.94      1885
 Is Patronizing       0.94      0.62      0.74       563

       accuracy                           0.90      2448
      macro avg       0.92      0.80      0.84      2448
   weighted avg       0.91      0.90      0.89      2448

[[1861   24]
 [ 215  348]]


In [ ]:
print(classification_report(y_test, y_pred_xgb, target_names=class_names))
print(confusion_matrix(y_test, y_pred_xgb))

                 precision    recall  f1-score   support

Not Patronizing       0.82      0.99      0.89      1885
 Is Patronizing       0.84      0.25      0.39       563

       accuracy                           0.82      2448
      macro avg       0.83      0.62      0.64      2448
   weighted avg       0.82      0.82      0.78      2448

[[1858   27]
 [ 420  143]]


In [ ]:
print(classification_report(y_test, y_pred_lr, target_names=class_names))
print(confusion_matrix(y_test, y_pred_lr))

                 precision    recall  f1-score   support

Not Patronizing       0.90      0.92      0.91      1885
 Is Patronizing       0.71      0.67      0.69       563

       accuracy                           0.86      2448
      macro avg       0.81      0.79      0.80      2448
   weighted avg       0.86      0.86      0.86      2448

[[1733  152]
 [ 186  377]]


In [ ]:
print(classification_report(y_test, y_pred_dt, target_names=class_names))
print(confusion_matrix(y_test, y_pred_dt))

                 precision    recall  f1-score   support

Not Patronizing       0.94      0.89      0.92      1885
 Is Patronizing       0.69      0.82      0.75       563

       accuracy                           0.87      2448
      macro avg       0.82      0.85      0.83      2448
   weighted avg       0.88      0.87      0.88      2448

[[1677  208]
 [ 103  460]]


In [ ]:
print(classification_report(y_test, y_pred_np, target_names=class_names))
print(confusion_matrix(y_test, y_pred_np))

                 precision    recall  f1-score   support

Not Patronizing       0.94      0.55      0.69      1885
 Is Patronizing       0.37      0.89      0.52       563

       accuracy                           0.63      2448
      macro avg       0.66      0.72      0.61      2448
   weighted avg       0.81      0.63      0.65      2448

[[1032  853]
 [  63  500]]
