In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from wordcloud import WordCloud

#to data preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#NLP tools
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

#train split and fit models
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

#model selection
from sklearn.metrics import confusion_matrix, accuracy_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
!cp gdrive/MyDrive/preparedDataSet3.pkl .
import pandas as pd

In [4]:
dataset = pd.read_pickle("preparedDataSet3.pkl")
dataset.head(10)

par_id                                           sentence  label
8738   9649  "an analysis of requests by federal officials ...      0
1184   6715  so assured government assistance in future for...      1
2572   3489  mr vigbedor urged the traditional leaders to b...      1
1103   1237  "mai chen , founder of myadvice.legal , said "...      0
5173   5708  the study showed that as many as 80 percent of...      0
8800   9723  following the main launch , at which the exhib...      0
711     790  """ we know that the success of any society de...      0
7049   7796  "the newspaper report came amid concerns over ...      0
7262   8029  """ we are proud to host an artist like kesha ...      0
6963   7703  severe cold wave is sweeping over kurigram cau...      0

In [5]:
dataset.shape

(12236, 3)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12236 entries, 8738 to 371
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   par_id    12236 non-null  object
 1   sentence  12236 non-null  object
 2   label     12236 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 382.4+ KB


In [7]:
dataset.describe().T

count      mean      std  min  25%  50%  75%  max
label  12236.0  0.225564  0.41797  0.0  0.0  0.0  0.0  1.0

In [8]:
dt_trasformed = dataset[['label', 'sentence']]
y = dt_trasformed.iloc[:, :-1].values

In [9]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = np.array(ct.fit_transform(y))

In [10]:
y[:10]

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [11]:
print(y)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]


In [12]:
y_df = pd.DataFrame(y)

In [13]:
np.array(y_df[0])

array([1., 0., 0., ..., 1., 1., 0.])

In [14]:
np.array(y_df[1])

array([0., 1., 1., ..., 0., 0., 1.])

In [15]:
dataset['sentence'].values

array(['"an analysis of requests by federal officials for local jails to keep immigrants suspected of violating us immigration law in custody found half of the so-called "" holds "" were placed on people who had been arrested but actually had no criminal conviction ."',
       'so assured government assistance in future for such initiatives . according to amod kanth , founder and general secretary , prayas jac society , said the library will instill a sense of confidence in the homeless and will help in changing their perspective towards life ."',
       'mr vigbedor urged the traditional leaders to be ambassadors in their respective communities to help reduce stigma and restore hope to such vulnerable groups .',
       ...,
       'but he said the findings should not be taken as a sign that women should seek an appendectomy or tonsillectomy thinking it could increase their chances of becoming pregnant .',
       'it is more like a town than a refugee camp .',
       ' space of a week 

In [16]:
cv = CountVectorizer(max_features = 2000)
X = cv.fit_transform(dataset['sentence'].values).toarray()

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y_df[1], test_size = 0.10, random_state = 0)

Finding the best models to predict 

Naive Bayes



In [18]:
classifier_np = GaussianNB()
classifier_np.fit(X_train, y_train)

GaussianNB()

Decision Tree

In [19]:
classifier_dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

KNN

In [20]:
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier()

Logistic Regression



In [21]:
classifier_lr = LogisticRegression(random_state = 0)
classifier_lr.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

Random Forest



In [22]:
classifier_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

SVM Classifier



In [23]:
classifier_svm = svm.SVC()
classifier_svm.fit(X_train, y_train)

SVC()

XGBoost Classifier



In [24]:
classifier_xgb= XGBClassifier()
classifier_xgb.fit(X_train, y_train)

XGBClassifier()

Making the Confusion Matrix for each model


In [25]:
#Naive Bayes
y_pred_np = classifier_np.predict(X_test)
cm = confusion_matrix(y_test, y_pred_np)
print(cm)

[[500 428]
 [ 34 262]]


In [26]:
#KNN
y_pred_knn = classifier_knn.predict(X_test)
cm = confusion_matrix(y_test, y_pred_knn)
print(cm)

[[856  72]
 [120 176]]


In [27]:
#XGBoost Classifier
y_pred_xgb = classifier_xgb.predict(X_test)
cm = confusion_matrix(y_test, y_pred_xgb)
print(cm)

[[916  12]
 [224  72]]


In [28]:
#SVM
y_pred_svm = classifier_svm.predict(X_test)
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)

[[919   9]
 [103 193]]


In [29]:
#Logistic Regression
y_pred_lr=classifier_lr.predict(X_test)
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)

[[863  65]
 [ 94 202]]


In [30]:
#Decision Tree
y_pred_dt = classifier_dt.predict(X_test)
cm = confusion_matrix(y_test, y_pred_dt)
print(cm)

[[832  96]
 [ 52 244]]


In [31]:
#Random Florest
y_pred_rf = classifier_rf.predict(X_test)
cm = confusion_matrix(y_test, y_pred_rf)
print(cm)

[[922   6]
 [ 73 223]]


In [32]:
rf_score = accuracy_score(y_test, y_pred_rf)
knn_score = accuracy_score(y_test, y_pred_knn)
svm_score = accuracy_score(y_test, y_pred_svm)
xgb_score = accuracy_score(y_test, y_pred_xgb)
lr_score = accuracy_score(y_test, y_pred_lr)
dt_score = accuracy_score(y_test, y_pred_dt)
np_score = accuracy_score(y_test, y_pred_np)

print('Random Forest Accuracy: ', str(rf_score))
print('K Nearest Neighbours Accuracy: ', str(knn_score))
print('Support Vector Machine Accuracy: ', str(svm_score))
print('XGBoost Classifier Accuracy: ', str(xgb_score))
print('Logistic Regression Accuracy: ',str(lr_score))
print('Decision Tree Accuracy: ', str(dt_score))
print('Naive Bayes Accuracy: ', str(np_score))

Random Forest Accuracy:  0.9354575163398693
K Nearest Neighbours Accuracy:  0.8431372549019608
Support Vector Machine Accuracy:  0.9084967320261438
XGBoost Classifier Accuracy:  0.8071895424836601
Logistic Regression Accuracy:  0.8700980392156863
Decision Tree Accuracy:  0.8790849673202614
Naive Bayes Accuracy:  0.6225490196078431


In [33]:
from sklearn.metrics import classification_report, confusion_matrix
class_names = ['Not Patronizing','Is Patronizing']
print(classification_report(y_test, y_pred_rf, target_names=class_names))
print(confusion_matrix(y_test, y_pred_rf))

                 precision    recall  f1-score   support

Not Patronizing       0.93      0.99      0.96       928
 Is Patronizing       0.97      0.75      0.85       296

       accuracy                           0.94      1224
      macro avg       0.95      0.87      0.90      1224
   weighted avg       0.94      0.94      0.93      1224

[[922   6]
 [ 73 223]]


In [34]:
print(classification_report(y_test, y_pred_knn, target_names=class_names))
print(confusion_matrix(y_test, y_pred_knn))

                 precision    recall  f1-score   support

Not Patronizing       0.88      0.92      0.90       928
 Is Patronizing       0.71      0.59      0.65       296

       accuracy                           0.84      1224
      macro avg       0.79      0.76      0.77      1224
   weighted avg       0.84      0.84      0.84      1224

[[856  72]
 [120 176]]


In [35]:
print(classification_report(y_test, y_pred_svm, target_names=class_names))
print(confusion_matrix(y_test, y_pred_svm))

                 precision    recall  f1-score   support

Not Patronizing       0.90      0.99      0.94       928
 Is Patronizing       0.96      0.65      0.78       296

       accuracy                           0.91      1224
      macro avg       0.93      0.82      0.86      1224
   weighted avg       0.91      0.91      0.90      1224

[[919   9]
 [103 193]]


In [36]:
print(classification_report(y_test, y_pred_xgb, target_names=class_names))
print(confusion_matrix(y_test, y_pred_xgb))

                 precision    recall  f1-score   support

Not Patronizing       0.80      0.99      0.89       928
 Is Patronizing       0.86      0.24      0.38       296

       accuracy                           0.81      1224
      macro avg       0.83      0.62      0.63      1224
   weighted avg       0.82      0.81      0.76      1224

[[916  12]
 [224  72]]


In [37]:
print(classification_report(y_test, y_pred_lr, target_names=class_names))
print(confusion_matrix(y_test, y_pred_lr))

                 precision    recall  f1-score   support

Not Patronizing       0.90      0.93      0.92       928
 Is Patronizing       0.76      0.68      0.72       296

       accuracy                           0.87      1224
      macro avg       0.83      0.81      0.82      1224
   weighted avg       0.87      0.87      0.87      1224

[[863  65]
 [ 94 202]]


In [38]:
print(classification_report(y_test, y_pred_dt, target_names=class_names))
print(confusion_matrix(y_test, y_pred_dt))

                 precision    recall  f1-score   support

Not Patronizing       0.94      0.90      0.92       928
 Is Patronizing       0.72      0.82      0.77       296

       accuracy                           0.88      1224
      macro avg       0.83      0.86      0.84      1224
   weighted avg       0.89      0.88      0.88      1224

[[832  96]
 [ 52 244]]


In [39]:
print(classification_report(y_test, y_pred_np, target_names=class_names))
print(confusion_matrix(y_test, y_pred_np))

                 precision    recall  f1-score   support

Not Patronizing       0.94      0.54      0.68       928
 Is Patronizing       0.38      0.89      0.53       296

       accuracy                           0.62      1224
      macro avg       0.66      0.71      0.61      1224
   weighted avg       0.80      0.62      0.65      1224

[[500 428]
 [ 34 262]]
