In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from wordcloud import WordCloud

#to data preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#NLP tools
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

#train split and fit models
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

#model selection
from sklearn.metrics import confusion_matrix, accuracy_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
!cp gdrive/MyDrive/prepared_DPM_preprocessing_newDfTrain_80.pkl .
!cp gdrive/MyDrive/prepared_DPM_preprocessing_newDfTest_20.pkl .
import pandas as pd

In [4]:
DfTrain = pd.read_pickle("prepared_DPM_preprocessing_newDfTrain_80.pkl")
DfTrain.head(10)

par_id                                           sentence  label
5137   5668  the contest will be featuring three categories...      0
6613   7323  other companies have not made formal announcem...      0
1466    952   eoghan odriscoll has been to hell and back bu...      1
3594   5460   again the stateless rohingya are on the run h...      1
4224   6133   dignity and hope despair and anger have set i...      1
728     810  q how much shift tanzania had witnessed in pul...      0
5344   5898  for the first time ever in bangladesh a daylon...      0
1144   1282  proposal made to make new constitution facilit...      0
368     409  in her apology letter that followed she dug he...      0
5014   5532  i bid you fraternal greetings hon alex bapula ...      0

In [5]:
DfTrain.shape

(13468, 3)

In [6]:
DfTrain.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13468 entries, 5137 to 2631
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   par_id    13468 non-null  object
 1   sentence  13468 non-null  object
 2   label     13468 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 420.9+ KB


In [7]:
DfTrain.describe().T

count     mean       std  min  25%  50%  75%  max
label  13468.0  0.49161  0.499948  0.0  0.0  0.0  1.0  1.0

In [8]:
dt_trasformed = DfTrain[['label', 'sentence']]
y = dt_trasformed.iloc[:, :-1].values

In [9]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = np.array(ct.fit_transform(y))

In [10]:
y[:10]

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [11]:
print(y)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [1. 0.]]


In [12]:
y_df = pd.DataFrame(y)

In [13]:
np.array(y_df[0])

array([1., 1., 0., ..., 0., 0., 1.])

In [14]:
np.array(y_df[1])

array([0., 0., 1., ..., 1., 1., 0.])

In [15]:
DfTrain['sentence'].values

array(['the contest will be featuring three categories the blind the deaf and people living with albinism the overall winner will become an ambassador for the disabled and will have the duty of educating the public on matters that affect people living with physical disabilities ',
       'other companies have not made formal announcements but were expected to adjust prices similarly since most of the fuel products in the philippines are imported and are thus vulnerable to similar supplydemand and foreign exchange forces ',
       ' eoghan odriscoll has been to hell and back but he is', ...,
       ' brand ambassador for the body shop pakistan but above all muniba is a loving mother fulfilling all her responsibilities to tee clearly there is no stopping her',
       ' bridges the gap between rich and poor sustained and impoverished fulfilled and needy this experience should then inspire compassion and mercy which is manifest by generosity of wealth and time to help those in need',
     

In [16]:
cv = CountVectorizer(max_features = 2000)
X = cv.fit_transform(DfTrain['sentence'].values).toarray()

In [17]:
X_train = X 

y_train = y_df[1]



In [18]:
DfTest = pd.read_pickle("prepared_DPM_preprocessing_newDfTest_20.pkl")
DfTest.head(10)

par_id                                           sentence  label
1927   9694  iain duncan smith resigns as work and pensions...      0
2207  10006  notions of fenian revolt were current and of k...      0
1991   9767  it was a tridional n leage budget proelite cla...      0
420    8035  tamil population growth was low from 1981 to 2...      0
1522   9246  crisismigrants and refugees wait to board a bu...      0
754    8408  she said on the commendations of the women win...      0
494    8117  at that pivotal moment dakota and her hopeless...      0
107    7694  ms mishra said it was a lonely experience arri...      0
207    2879   when you comfortably watch starvation waste y...      1
909    8575  in january the white house proposed a pathway ...      0

In [19]:
dt_trasformed = DfTest[['label', 'sentence']]
y = dt_trasformed.iloc[:, :-1].values

In [20]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = np.array(ct.fit_transform(y))

In [21]:
y_df = pd.DataFrame(y)

In [22]:
cv = CountVectorizer(max_features = 2000)
X = cv.fit_transform(DfTest['sentence'].values).toarray()

In [25]:
X_test = X
y_test = y_df[1]

Finding the best models to predict 

Naive Bayes



In [26]:
classifier_np = GaussianNB()
classifier_np.fit(X_train, y_train)

GaussianNB()

Decision Tree

In [27]:
classifier_dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

KNN

In [28]:
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier()

Logistic Regression



In [29]:
classifier_lr = LogisticRegression(random_state = 0)
classifier_lr.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

Random Forest



In [30]:
classifier_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

SVM Classifier



In [31]:
classifier_svm = svm.SVC()
classifier_svm.fit(X_train, y_train)

SVC()

XGBoost Classifier



In [32]:
classifier_xgb= XGBClassifier()
classifier_xgb.fit(X_train, y_train)

XGBClassifier()

Making the Confusion Matrix for each model


In [33]:
#Naive Bayes
y_pred_np = classifier_np.predict(X_test)
cm = confusion_matrix(y_test, y_pred_np)
print(cm)

[[2280  349]
 [1325  334]]


In [34]:
#KNN
y_pred_knn = classifier_knn.predict(X_test)
cm = confusion_matrix(y_test, y_pred_knn)
print(cm)

[[1497 1132]
 [1018  641]]


In [35]:
#XGBoost Classifier
y_pred_xgb = classifier_xgb.predict(X_test)
cm = confusion_matrix(y_test, y_pred_xgb)
print(cm)

[[  60 2569]
 [  21 1638]]


In [36]:
#SVM
y_pred_svm = classifier_svm.predict(X_test)
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)

[[1503 1126]
 [ 736  923]]


In [37]:
#Logistic Regression
y_pred_lr=classifier_lr.predict(X_test)
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)

[[ 908 1721]
 [ 557 1102]]


In [38]:
#Decision Tree
y_pred_dt = classifier_dt.predict(X_test)
cm = confusion_matrix(y_test, y_pred_dt)
print(cm)

[[ 786 1843]
 [ 354 1305]]


In [39]:
#Random Florest
y_pred_rf = classifier_rf.predict(X_test)
cm = confusion_matrix(y_test, y_pred_rf)
print(cm)

[[1561 1068]
 [ 754  905]]


In [40]:
rf_score = accuracy_score(y_test, y_pred_rf)
knn_score = accuracy_score(y_test, y_pred_knn)
svm_score = accuracy_score(y_test, y_pred_svm)
xgb_score = accuracy_score(y_test, y_pred_xgb)
lr_score = accuracy_score(y_test, y_pred_lr)
dt_score = accuracy_score(y_test, y_pred_dt)
np_score = accuracy_score(y_test, y_pred_np)

print('Random Forest Accuracy: ', str(rf_score))
print('K Nearest Neighbours Accuracy: ', str(knn_score))
print('Support Vector Machine Accuracy: ', str(svm_score))
print('XGBoost Classifier Accuracy: ', str(xgb_score))
print('Logistic Regression Accuracy: ',str(lr_score))
print('Decision Tree Accuracy: ', str(dt_score))
print('Naive Bayes Accuracy: ', str(np_score))

Random Forest Accuracy:  0.5750932835820896
K Nearest Neighbours Accuracy:  0.4986007462686567
Support Vector Machine Accuracy:  0.5657649253731343
XGBoost Classifier Accuracy:  0.39598880597014924
Logistic Regression Accuracy:  0.46875
Decision Tree Accuracy:  0.48763992537313433
Naive Bayes Accuracy:  0.6096082089552238


In [41]:
from sklearn.metrics import classification_report, confusion_matrix
class_names = ['Not Patronizing','Is Patronizing']
print(classification_report(y_test, y_pred_rf, target_names=class_names))
print(confusion_matrix(y_test, y_pred_rf))

                 precision    recall  f1-score   support

Not Patronizing       0.67      0.59      0.63      2629
 Is Patronizing       0.46      0.55      0.50      1659

       accuracy                           0.58      4288
      macro avg       0.57      0.57      0.56      4288
   weighted avg       0.59      0.58      0.58      4288

[[1561 1068]
 [ 754  905]]


In [42]:
print(classification_report(y_test, y_pred_knn, target_names=class_names))
print(confusion_matrix(y_test, y_pred_knn))

                 precision    recall  f1-score   support

Not Patronizing       0.60      0.57      0.58      2629
 Is Patronizing       0.36      0.39      0.37      1659

       accuracy                           0.50      4288
      macro avg       0.48      0.48      0.48      4288
   weighted avg       0.50      0.50      0.50      4288

[[1497 1132]
 [1018  641]]


In [43]:
print(classification_report(y_test, y_pred_svm, target_names=class_names))
print(confusion_matrix(y_test, y_pred_svm))

                 precision    recall  f1-score   support

Not Patronizing       0.67      0.57      0.62      2629
 Is Patronizing       0.45      0.56      0.50      1659

       accuracy                           0.57      4288
      macro avg       0.56      0.56      0.56      4288
   weighted avg       0.59      0.57      0.57      4288

[[1503 1126]
 [ 736  923]]


In [44]:
print(classification_report(y_test, y_pred_xgb, target_names=class_names))
print(confusion_matrix(y_test, y_pred_xgb))

                 precision    recall  f1-score   support

Not Patronizing       0.74      0.02      0.04      2629
 Is Patronizing       0.39      0.99      0.56      1659

       accuracy                           0.40      4288
      macro avg       0.57      0.51      0.30      4288
   weighted avg       0.60      0.40      0.24      4288

[[  60 2569]
 [  21 1638]]


In [45]:
print(classification_report(y_test, y_pred_lr, target_names=class_names))
print(confusion_matrix(y_test, y_pred_lr))

                 precision    recall  f1-score   support

Not Patronizing       0.62      0.35      0.44      2629
 Is Patronizing       0.39      0.66      0.49      1659

       accuracy                           0.47      4288
      macro avg       0.51      0.50      0.47      4288
   weighted avg       0.53      0.47      0.46      4288

[[ 908 1721]
 [ 557 1102]]


In [46]:
print(classification_report(y_test, y_pred_dt, target_names=class_names))
print(confusion_matrix(y_test, y_pred_dt))

                 precision    recall  f1-score   support

Not Patronizing       0.69      0.30      0.42      2629
 Is Patronizing       0.41      0.79      0.54      1659

       accuracy                           0.49      4288
      macro avg       0.55      0.54      0.48      4288
   weighted avg       0.58      0.49      0.47      4288

[[ 786 1843]
 [ 354 1305]]


In [47]:
print(classification_report(y_test, y_pred_np, target_names=class_names))
print(confusion_matrix(y_test, y_pred_np))

                 precision    recall  f1-score   support

Not Patronizing       0.63      0.87      0.73      2629
 Is Patronizing       0.49      0.20      0.29      1659

       accuracy                           0.61      4288
      macro avg       0.56      0.53      0.51      4288
   weighted avg       0.58      0.61      0.56      4288

[[2280  349]
 [1325  334]]
