In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from wordcloud import WordCloud

#to data preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#NLP tools
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

#train split and fit models
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

#model selection
from sklearn.metrics import confusion_matrix, accuracy_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
!cp gdrive/MyDrive/prepared_DPM_preprocessing3.pkl .
import pandas as pd

In [4]:
dataset = pd.read_pickle("prepared_DPM_preprocessing3.pkl")
dataset.head(10)

par_id                                           sentence  label
7051   7799   i m not proud of what happened over the weeke...      0
1490   1676   cbpr methods can increase our understanding o...      0
2216   9126   in big cities most of the country is rural an...      1
5373   1824   i am climbing all these summits to raise fund...      1
4108    763   economies that could have otherwise done well...      1
1327   4023   her compassionate outreach her topic is mercy...      1
8284   9157  should the skeleton be positively identified a...      0
6412   7094  the irish immigrant also faced a charge of att...      0
9005   9952  while there are an estimated 11 million people...      0
5963   6601  one reason senator sessions said is that immig...      0

In [5]:
dataset.shape

(17756, 3)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17756 entries, 7051 to 6270
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   par_id    17756 non-null  object
 1   sentence  17756 non-null  object
 2   label     17756 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 554.9+ KB


In [7]:
dataset.describe().T

count      mean       std  min  25%  50%  75%  max
label  17756.0  0.466321  0.498879  0.0  0.0  0.0  1.0  1.0

In [8]:
dt_trasformed = dataset[['label', 'sentence']]
y = dt_trasformed.iloc[:, :-1].values

In [9]:
y

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [10]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = np.array(ct.fit_transform(y))

In [11]:
y[:10]

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [12]:
print(y)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [13]:
y_df = pd.DataFrame(y)

In [14]:
np.array(y_df[0])

array([1., 1., 0., ..., 1., 1., 1.])

In [15]:
np.array(y_df[1])

array([0., 0., 1., ..., 0., 0., 0.])

In [ ]:
dataset['sentence'].values

array([' i m not proud of what happened over the weekend and i wish to extend my apology to women all over south africa and the world there are better ways to deal with disputes and disagreements ',
       ' cbpr methods can increase our understanding of risk and protective factors in refugee and immigrant communities and contribute to development of culturally appropriate programming to address health disparities shirazi said via email my use of cbpr has taken an innovative approach to addressing health disparities and building evidencebased community health programming ',
       ' in big cities most of the country is rural and most of the population is illiterate and hopeless',
       ...,
       'presently what aspect of smart cities do you think is most vulnerable ',
       'like many in sao paulo s army of the homeless she sees her squat not as something illegal but as a real fight for housing ',
       'many of the devices are vulnerable based on siemens alerts and do not have th

In [16]:
cv = CountVectorizer(max_features = 2000)
X = cv.fit_transform(dataset['sentence'].values).toarray()

In [17]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
y_df[1]

0        0.0
1        0.0
2        1.0
3        1.0
4        1.0
        ... 
17751    1.0
17752    0.0
17753    0.0
17754    0.0
17755    0.0
Name: 1, Length: 17756, dtype: float64

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y_df[1], test_size = 0.30, random_state = 0)

In [21]:
y_train

9728     1.0
17359    1.0
4908     1.0
4470     1.0
14211    1.0
        ... 
9225     0.0
13123    1.0
9845     1.0
10799    0.0
2732     1.0
Name: 1, Length: 12429, dtype: float64

In [20]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Finding the best models to predict 

Naive Bayes



In [ ]:
classifier_np = GaussianNB()
classifier_np.fit(X_train, y_train)

GaussianNB()

Decision Tree

In [ ]:
classifier_dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

KNN

In [ ]:
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier()

Logistic Regression



In [ ]:
classifier_lr = LogisticRegression(random_state = 0)
classifier_lr.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

Random Forest



In [ ]:
classifier_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

SVM Classifier



In [ ]:
classifier_svm = svm.SVC()
classifier_svm.fit(X_train, y_train)

SVC()

XGBoost Classifier



In [ ]:
classifier_xgb= XGBClassifier()
classifier_xgb.fit(X_train, y_train)

XGBClassifier()

Making the Confusion Matrix for each model


In [ ]:
#Naive Bayes
y_pred_np = classifier_np.predict(X_test)
cm = confusion_matrix(y_test, y_pred_np)
print(cm)

[[1929  895]
 [ 241 2262]]


In [ ]:
#KNN
y_pred_knn = classifier_knn.predict(X_test)
cm = confusion_matrix(y_test, y_pred_knn)
print(cm)

[[1124 1700]
 [ 153 2350]]


In [ ]:
#XGBoost Classifier
y_pred_xgb = classifier_xgb.predict(X_test)
cm = confusion_matrix(y_test, y_pred_xgb)
print(cm)

[[2235  589]
 [ 587 1916]]


In [ ]:
#SVM
y_pred_svm = classifier_svm.predict(X_test)
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)

[[2516  308]
 [ 214 2289]]


In [ ]:
#Logistic Regression
y_pred_lr=classifier_lr.predict(X_test)
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)

[[2436  388]
 [ 289 2214]]


In [ ]:
#Decision Tree
y_pred_dt = classifier_dt.predict(X_test)
cm = confusion_matrix(y_test, y_pred_dt)
print(cm)

[[2310  514]
 [ 301 2202]]


In [ ]:
#Random Florest
y_pred_rf = classifier_rf.predict(X_test)
cm = confusion_matrix(y_test, y_pred_rf)
print(cm)

[[2643  181]
 [ 290 2213]]


In [ ]:
rf_score = accuracy_score(y_test, y_pred_rf)
knn_score = accuracy_score(y_test, y_pred_knn)
svm_score = accuracy_score(y_test, y_pred_svm)
xgb_score = accuracy_score(y_test, y_pred_xgb)
lr_score = accuracy_score(y_test, y_pred_lr)
dt_score = accuracy_score(y_test, y_pred_dt)
np_score = accuracy_score(y_test, y_pred_np)

print('Random Forest Accuracy: ', str(rf_score))
print('K Nearest Neighbours Accuracy: ', str(knn_score))
print('Support Vector Machine Accuracy: ', str(svm_score))
print('XGBoost Classifier Accuracy: ', str(xgb_score))
print('Logistic Regression Accuracy: ',str(lr_score))
print('Decision Tree Accuracy: ', str(dt_score))
print('Naive Bayes Accuracy: ', str(np_score))

Random Forest Accuracy:  0.9115825042237657
K Nearest Neighbours Accuracy:  0.6521494274450911
Support Vector Machine Accuracy:  0.9020086352543646
XGBoost Classifier Accuracy:  0.7792378449408672
Logistic Regression Accuracy:  0.8729115825042237
Decision Tree Accuracy:  0.84700581941055
Naive Bayes Accuracy:  0.7867467617796133


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
class_names = ['Not Patronizing','Is Patronizing']
print(classification_report(y_test, y_pred_rf, target_names=class_names))
print(confusion_matrix(y_test, y_pred_rf))

                 precision    recall  f1-score   support

Not Patronizing       0.90      0.94      0.92      2824
 Is Patronizing       0.92      0.88      0.90      2503

       accuracy                           0.91      5327
      macro avg       0.91      0.91      0.91      5327
   weighted avg       0.91      0.91      0.91      5327

[[2643  181]
 [ 290 2213]]


In [ ]:
print(classification_report(y_test, y_pred_knn, target_names=class_names))
print(confusion_matrix(y_test, y_pred_knn))

                 precision    recall  f1-score   support

Not Patronizing       0.88      0.40      0.55      2824
 Is Patronizing       0.58      0.94      0.72      2503

       accuracy                           0.65      5327
      macro avg       0.73      0.67      0.63      5327
   weighted avg       0.74      0.65      0.63      5327

[[1124 1700]
 [ 153 2350]]


In [ ]:
print(classification_report(y_test, y_pred_svm, target_names=class_names))
print(confusion_matrix(y_test, y_pred_svm))

                 precision    recall  f1-score   support

Not Patronizing       0.92      0.89      0.91      2824
 Is Patronizing       0.88      0.91      0.90      2503

       accuracy                           0.90      5327
      macro avg       0.90      0.90      0.90      5327
   weighted avg       0.90      0.90      0.90      5327

[[2516  308]
 [ 214 2289]]


In [ ]:
print(classification_report(y_test, y_pred_xgb, target_names=class_names))
print(confusion_matrix(y_test, y_pred_xgb))

                 precision    recall  f1-score   support

Not Patronizing       0.79      0.79      0.79      2824
 Is Patronizing       0.76      0.77      0.77      2503

       accuracy                           0.78      5327
      macro avg       0.78      0.78      0.78      5327
   weighted avg       0.78      0.78      0.78      5327

[[2235  589]
 [ 587 1916]]


In [ ]:
print(classification_report(y_test, y_pred_lr, target_names=class_names))
print(confusion_matrix(y_test, y_pred_lr))

                 precision    recall  f1-score   support

Not Patronizing       0.89      0.86      0.88      2824
 Is Patronizing       0.85      0.88      0.87      2503

       accuracy                           0.87      5327
      macro avg       0.87      0.87      0.87      5327
   weighted avg       0.87      0.87      0.87      5327

[[2436  388]
 [ 289 2214]]


In [ ]:
print(classification_report(y_test, y_pred_dt, target_names=class_names))
print(confusion_matrix(y_test, y_pred_dt))

                 precision    recall  f1-score   support

Not Patronizing       0.88      0.82      0.85      2824
 Is Patronizing       0.81      0.88      0.84      2503

       accuracy                           0.85      5327
      macro avg       0.85      0.85      0.85      5327
   weighted avg       0.85      0.85      0.85      5327

[[2310  514]
 [ 301 2202]]


In [ ]:
print(classification_report(y_test, y_pred_np, target_names=class_names))
print(confusion_matrix(y_test, y_pred_np))

                 precision    recall  f1-score   support

Not Patronizing       0.89      0.68      0.77      2824
 Is Patronizing       0.72      0.90      0.80      2503

       accuracy                           0.79      5327
      macro avg       0.80      0.79      0.79      5327
   weighted avg       0.81      0.79      0.79      5327

[[1929  895]
 [ 241 2262]]
